### ISSUE TITLE
カスタム管理ポリシー作成を追加

### ISSUE THREAD

**Issue by minom3** [serverworks/iam-policies#3]
administratorユーザーが管理ポリシーをattach/detachできる問題対策

1)カスタム管理ポリシー「ServerworksControlePolicy」を作る
ーーー
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Action": [
                "iam:*"
            ],
            "Resource": [
                "arn:aws:iam::123456789012:user/*",
                "arn:aws:iam::123456789012:group/*"
            ],
            "Condition": {
                "ArnLike": {
                    "iam:PolicyArn": [
                        "arn:aws:iam::aws:policy/*",
                        "arn:aws:iam::123456789012:policy/*"
                    ]
                }
            }
        }
    ]
}
ーーー

**Comment by akuira** [comment]
ポリシーだけ先に作成します。
実際に追加するための処理は以下のissueで行います。
https://github.com/serverworks/cs/issues/15
