### ISSUE TITLE
poweruser-groupポリシー中の123456789123を置換

### ISSUE THREAD

**Issue by minom3** [serverworks/iam-policies#8]
poweruser−groupポリシー中の123456789123を指定されたAWSアカウント12桁に置換

**Comment by minom3** [comment]
この処理自体はCSレポジトリー
CSレポジトリーの修正が完了したら、このissuesと合わせて、
20160713_minomブランチをcloseしてください。

**Comment by akuira** [comment]
https://github.com/serverworks/cs/issues/13
で対応しました
