### ISSUE TITLE
編集不可ユーザーにcloudautomatorを追加

### ISSUE THREAD

**Issue by minom3** [serverworks/iam-policies#9]
serverworks、sky365だけじゃなく、cloudautomatorユーザーも編集不可に

**Comment by minom3** [comment]
"Resource": [
        "arn:aws:iam::123456789123:user/serverworks",
        "arn:aws:iam::123456789123:user/sky365"
      ]
ここにcloudautomatorも追加したい。
コード上ではユーザー指定が直接指定じゃないのでソースの確認が必要かと。

        "arn:aws:iam::123456789123:user/[serverworks-user]",
        "arn:aws:iam::123456789123:user/[ops-user]"

**Comment by akuira** [comment]
ユーザー名の置換は以下のリポジトリで対応してます。

https://github.com/serverworks/cs/issues/16
